build-job:
  image: gcc
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
  script:
    - cd scheduler++
    - cmake --preset default
    - cmake --build build