build-job:
  image: gcc
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
  script:
    - cd scheduler++
    - cmake -B build -DCMAKE_CXX_STANDARD=20
    - cmake --build build