#!/bin/bash/env python3
from .commands import ArgumentParser, streams_command, schedule_command, api_command

if __name__ == "__main__":
    argumentParser = ArgumentParser()
    # TODO: make arguments generated by the specific scheduler
    args = argumentParser.parse_arguments()

    if args.command == "schedule":
        schedule_command(args)
    elif args.command == "streams":
        streams_command(args)
    elif args.command == "api":
        api_command(args)